global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG
  filePath: log/traefik.log

api:
  dashboard: true # Optional can be disabled
  insecure: true # Optional can be disabled
  debug: false # Optional can be Enabled if needed for troubleshooting

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: demo # Optional; Only use the "proxy" Docker network, even if containers are on multiple networks.

certificatesResolvers:
  letencrypt:
    acme:
      email: admin@acme.com
      storage: /certs/acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      httpChallenge:
        entryPoint: web