# Project URL: https://github.com/traefik/traefik
# Docs URL: https://doc.traefik.io/traefik/
# Use Case:
services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    networks: ['demo']
    security_opt:
      - no-new-privileges:true # Prevent escalate privileges using setuid or setgid binaries
    environment:
      - TZ=Europe/Madrid
    command:
      # STATIC CONFIGURATION
      # *** Logging configuration ***
      - --log.level=info # Logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
      - --log.filePath=/logs/traefik.log # Logging
      #- --log.format=json
      # *** API configuration ***
      - --api.insecure=true # Set access to traefic api wihout autentication (NO use Production)
      # *** Docker provider configuration ***
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false # Not want Traefik to expose ALL containers by default. Require containers to define 'traefik.enable=true' to be exposed
      #- --providers.docker.network=demo
      # *** Entrypoints configuration ***
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 80:80 # HTTP port
      - 8080:8080 # Web UI port (enabled by --api.insecure=true)
      - 443:443
    volumes:
      # *** General configuration ***
      #- /etc/localtime:/etc/localtime:ro # Uses the same timezone as the computer instance
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      - ./traefik-docker/logs:/logs # Storage for Traefik Logs
      #- ./traefik-docker/letsencrypt:/letsencrypt # Storage for Letsencrypt certificates
      #- ./traefik-docker/certs:/certs # Storage for certificates
      #- ./traefik-docker/traefik:/etc/traefik # Traefik configuration

  # https://github.com/docker-library/httpd
  backend1:
    image: httpd:2.4.63-alpine3.21
    container_name: backend1
    restart: always
    networks: ['demo']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend1.rule=Host(`backend1.localhost`) && Path(`/backend1`)"
      - "traefik.http.routers.backend1.entrypoints=web"
      - "traefik.http.services.backend1.loadbalancer.server.port=80"
      - "traefik.http.routers.backend1.middlewares=backend1-prefix"
      - "traefik.http.middlewares.backend1-prefix.stripprefix.prefixes=/backend1"
    volumes:
      - ../config/index1.html:/usr/local/apache2/htdocs/index.html

  # https://github.com/nginx/nginx
  backend2:
    image: nginx:1.27.4-alpine
    container_name: backend2
    restart: always
    networks: ['demo']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend2.rule=Host(`backend2.localhost`)"
      - "traefik.http.routers.backend2.entrypoints=web"
      - "traefik.http.services.backend2.loadbalancer.server.port=80"
      - "traefik.http.middlewares.backend2-redirect.redirectscheme.scheme=https"
    volumes:
      - ../config/index2.html:/usr/share/nginx/html/index.html

volumes:
  traefik-docker:

networks:
  demo:
    name: demo
    driver: bridge
