# Project URL: https://github.com/traefik/traefik
# Docs URL: https://doc.traefik.io/traefik/
# Use Case: http-challenge
services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    networks: ['demo']
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Madrid
    command:
      # STATIC CONFIGURATION
      # *** Logging configuration ***
      - --log.level=info # Logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
      #- --log.format=json
      # *** API configuration ***
      - --api.insecure=true
      # *** Docker provider configuration ***
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      # *** Entrypoints configuration ***
      - --entryPoints.web.address=:80 # web entrypoint handles http traffic over port 80
      - --entrypoints.websecure.address=:443 # websecure entrypoint handles https traffic over port 443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure # Redirect web to websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https # http will be redirected to https.
      # *** Certificate configuration ***
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=admin@acme.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      # *** General configuration ***
      #- /etc/localtime:/etc/localtime:ro # Uses the same timezone as the computer instance
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      #- ./traefik-docker/logs:/logs # Storage for Traefik Logs
      - ./traefik-docker/letsencrypt:/letsencrypt # Storage for Letsencrypt certificates
      #- ./traefik-docker/certs:/certs # Storage for certificates
      #- ./traefik-docker/traefik:/etc/traefik # Traefik configuration

  # https://github.com/nginxinc/docker-nginx
  backend1:
    image: nginx:1.27.4
    container_name: backend1
    restart: unless-stopped
    networks: ['demo']
    labels:
      # *** General Traefik configuration ***
      - traefik.enable=true # Explicitly instruct Traefik to expose this service
      # *** Router configuration ***
      - traefik.http.routers.backend1.entrypoints=websecure
      # curl -k -H Host:backend1.localhost https://127.0.0.1
      - traefik.http.routers.backend1.rule=Host(`backend1.localhost`) # Rule based on the Host of the request
      - traefik.http.routers.backend1.tls=true
      - traefik.http.routers.backend1.tls.certresolver=myresolver
      #- traefik.http.services.backend1.loadbalancer.server.port=80

volumes:
  traefik-docker:

networks:
  demo:
    name: demo
    driver: bridge
