# Project URL: https://github.com/traefik/traefik
# Docs URL: https://doc.traefik.io/traefik/
services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    networks: ['demo']
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Madrid
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      - ./traefik-docker/logs:/logs # Storage for Traefik Logs
      - ./traefik-docker/letsencrypt:/letsencrypt # Storage for Letsencrypt certificates
      - ./traefik-docker/certs:/certs # Storage for certificates
      - ./config/traefik2.yml:/traefik.yml:ro
      #- ./traefik-docker/traefik/traefik.yml:/etc/traefik/traefik.yml

volumes:
  traefik-data:

networks:
  demo:
    name: demo
    driver: bridge
