# Project URL: https://github.com/traefik/traefik
# Docs URL: https://doc.traefik.io/traefik/
# Use Case:
services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    networks: ['localhost_net']
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Madrid
    command: "--configFile=/config/traefik.yml"
    ports:
      - 80:80 # HTTP port
      - 8080:8080 # Web UI port (enabled by --api.insecure=true)
      - 443:443 # HTTPs port
    volumes:
      # *** General configuration ***
      #- /etc/localtime:/etc/localtime:ro # Uses the same timezone as the computer instance
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      - ./traefik-docker/logs:/logs # Storage for Traefik Logs
      - ./traefik-docker/letsencrypt:/letsencrypt # Storage for Letsencrypt certificates
      - ./traefik-docker/certs:/certs # Storage for certificates
      - ./traefik-docker/traefik-data:/etc/traefik # Traefik configuration
      # *** Traefik configuration ***
      - ./config/traefik4.yml:/config/traefik.yml:ro
      - ./config/localhost.crt:/certs/localhost.crt:ro
      - ./config/localhost.key:/certs/localhost.key:ro
    labels:
      # *** General Traefik configuration ***
      - traefik.enable=true
      # *** Router configuration ***
      - traefik.http.routers.traefik.rule=Host(`proxy.localhost`)
      - traefik.http.routers.traefik.entrypoints=websecure
      # *** Service configuration ***
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      # *** Rate Limiting configuration ***
      #- traefik.http.middlewares.ratelimit.ratelimit.average=100
      #- traefik.http.middlewares.ratelimit.ratelimit.burst=50

  # https://github.com/docker-library/httpd
  backend1:
    image: httpd:2.4.63-alpine3.21
    container_name: backend1
    restart: always
    networks: ['localhost_net']
    labels:
      # *** General Traefik configuration ***
      - traefik.enable=true # Explicitly instruct Traefik to expose this service
      # *** Router configuration ***
      - traefik.http.routers.backend1.entrypoints=websecure
      - traefik.http.routers.backend1.rule=Host(`backend1.localhost`) # Rule based on the Host of the request
      # *** Service configuration ***
      - traefik.http.services.backend1.loadbalancer.server.port=80
      # *** Healthcheck configuration ***
      #- traefik.http.services.backend1.loadbalancer.healthcheck.path=/health
      #- traefik.http.services.backend1.loadbalancer.healthcheck.interval=10s

volumes:
  traefik-docker:

networks:
  localhost_net: # Create it before we run docker-compose command: docker network create localhost_net
    name: localhost_net
    external: true
