# Project URL: https://github.com/traefik/traefik
# Docs URL: https://doc.traefik.io/traefik/
# Use Case:
services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    networks: ['demo']
    security_opt:
      - no-new-privileges:true # Prevent escalate privileges using setuid or setgid binaries
    environment:
      - TZ=Europe/Madrid
    ports:
      - 80:80 # HTTP port
      - 8080:8080 # Web UI port (enabled by --api.insecure=true)
      - 443:443 # HTTPs port
    volumes:
      # *** General configuration ***
      #- /etc/localtime:/etc/localtime:ro # Uses the same timezone as the computer instance
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      - ./traefik-docker/logs:/logs # Storage for Traefik Logs
      - ./traefik-docker/letsencrypt:/letsencrypt # Storage for Letsencrypt certificates
      - ./traefik-docker/certs:/certs # Storage for certificates
      # *** Traefik configuration **
      - ./config/traefik3.yml:/traefik.yml:ro               # static traefik configuration
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml:ro  # dynamic traefik configuration
      - ./config/acme.json:/etc/traefik/acme.json           # TLS certificate storage
    labels:
      - traefik.enable=true

      # define basic auth middleware for dashboard
      - traefik.http.middlewares.traefik-auth.basicauth.removeheader=true
      - traefik.http.middlewares.traefik-auth.basicauth.users=foobar:$$2y$$05$$z2KwKI.GmZ43BbwfmPPKw.CSl3rqQ0OhzBbdom.orfsMVKGLW/Xeu # CHANGE PASSWORD!! (user: foobar / pwd: foobar)
      # how to set a real password:
      # sudo apt-get install apache2-utils
      # htpasswd -Bnb username password | sed -e s/\\$/\\$\\$/g

      # define traefik dashboard router and service
      - traefik.http.routers.traefik.rule=Host(`acme.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=tlschallenge
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.middlewares=traefik-auth, secHeaders@file, autodetectContenttype@file
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  # https://github.com/traefik/whoami
  backend1:
    image: traefik/whoami:v1.10.4
    container_name: backend1
    restart: always
    networks: ['demo']
    labels:
      # *** General Traefik configuration ***
      - traefik.enable=true # Explicitly instruct Traefik to expose this service
      # *** Router configuration ***
      - traefik.http.routers.backend1.entrypoints=web-secure
      # curl -H Host:backend1.localhost https://127.0.0.1
      - traefik.http.routers.backend1.rule=Host(`backend1.localhost`) # Rule based on the Host of the request
      - traefik.http.routers.backend1.tls=true
      - traefik.http.routers.backend1.tls.certresolver=tlschallenge
      # *** Service configuration ***
      - traefik.http.services.backend1.loadbalancer.server.port=80
      # *** Middleware configuration ***
      - traefik.http.routers.backend1.middlewares=secHeaders@file

volumes:
  traefik-docker:

networks:
  demo:
    name: demo
    driver: bridge
