services:
  traefik:
    image: traefik:v2.5
    container_name: "traefik"
    restart: always
    networks: ['demo']
    command:
      - "--api.insecure=true" #Flag enables the web UI without authentication
      - "--providers.docker=true"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  demo:
    driver: bridge
